### ISSUE TITLE
Is there documentation on how to use this plugin?

### ISSUE THREAD

**Issue by kevintraver** [bcgraham/pry-keybind#1]

**Comment by bcgraham** [comment]
No - I will write some up!

**Comment by kevintraver** [comment]
Awesome! Thank you. This looks like a very useful plugin. Happy to help with any feedback.

**Comment by bcgraham** [comment]
It was built in 15-and-20-minute snatches of time over a long period, so the code could probably be simplified a lot, and there might un-idiomatic Readline integration, or duplication of functionality Readline provides but I didn’t know about when I wrote it.
![DDBDA84C-C4F4-47A8-A179-EAAB667B2BD6](https://user-images.githubusercontent.com/261376/142732759-a8206ba0-4624-4e1f-ada0-f8ff84196bba.jpeg)
This is a quickstart screenshot. It isn’t real documentation, but I won’t be able to put that together until later this weekend, hopefully (two young children, time ain’t what it used to be). Hopefully it gives the gist. The last few lines are me hitting alt-t.

**Comment by bcgraham** [comment]
This can help with a lot of repetitive pry and pry-byebug commands. Here’s a snippet:
```
PryKeybind.register(:WHEREAMI_HOTKEY, "\ew") { |pry_instance| pry_instance.run_command('whereami') };
PryKeybind.register(:UP, "\ek", save_input: true) { |pry_instance| pry_instance.run_command('up') };
PryKeybind.register(:DOWN, "\ej", save_input: true) { |pi| pi.run_command('down') };
PryKeybind.register(:NEXT, "\en", save_input: true) { |pi| pi.run_command('next') };
PryKeybind.register(:STEP, "\es", save_input: true) { |pi| pi.run_command('step') };
PryKeybind.register(:CONTINUE, "\ec", save_input: true) { |pi| pi.run_command('continue') };
```
Alt-enter to insert a newline literal:

```
PryKeybind.register(:NEWLINE, "\e\r") { Pryline.insert_text "\n" };
```
This is really dependent on terminal settings obviously. 

If none of this is useful, apologies, more legit documentation incoming!

**Comment by bcgraham** [comment]
Btw, the reason I fiddle with LOAD_PATH in the screen shot is to get around bundler environment restrictions. That’s not required normally.

**Comment by kevintraver** [comment]
Thank you for the instructions. I was able to get it working! 

I am now having an issue with binding the keys with the escape sequence like in your example (binding regular keys works fine).

**Comment by kevintraver** [comment]
My apologies, I believe it was a conflicting key binding and I was able to figure it out.

**Comment by kevintraver** [comment]
One other issue I am having

I have set up the following:

```PryKeybind.register(:EDIT, "\ee") { |pi| pi.run_command('edit')};```

This seems to be working great. When I press the key it fires off the command just fine.

But when I exit the editor, I have to press *enter* twice. It seems to add a newline at the end. 

When I just type `edit` and exit the editor, I only have to press *enter* once.

This might not be specifically a *pry-keybind* issue.

**Comment by bcgraham** [comment]
There are a _lot_ of tricky corner-cases resulting from `pry` getting out of sync with `Readline`, when that's never had be to considered before.

For example, in this case, the `edit` command provided by `pry` assigns the content to `pry.eval_string`. 
```ruby
def input_inspection(pry_instance)
  puts "\n\npry_instance.eval_string is now #{pry_instance.eval_string.inspect}"
  puts "\nReadline.line_buffer is now #{Readline.line_buffer.inspect}\n\n"
end

PryKeybind.register(:EDIT, "\ee") { |pi| pi.run_command("edit"); input_inspection(pi) }
```
In Pry's normal operation, `eval_string` only gets populated after `Readline.readline` has returned; after you call `edit`, it's expecting to populate `eval_string` and then execute its contents. But `Readline.readline` hasn't returned, and nothing will execute until you hit "enter."

Try this one:
```ruby
PryKeybind.register(:EDIT_BUFFER, "\ee") { |pi| pi.run_command("edit"); Pryline.replace_buffer(pi.eval_string.chomp); pi.eval_string = '' }
```

**Comment by bcgraham** [comment]
Here's one I have a hard time doing without:
```ruby
PryKeybind.register(:ACCEPT_LINE, "\cm", no_refresh: true) do |pry_instance|
  # puts "\nset keybindings accepting line\n"
  whole_buffer = "#{pry_instance.eval_string}#{Pryline.line_buffer}"
  begin
    if pry_instance.commands[Pryline.line_buffer]
      Pryline.accept_line
    elsif Pry::Code.complete_expression?(whole_buffer)
      if Pryline.line_buffer.chomp.lines.size > 1
        buffer = Pryline.line_buffer
        Pryline.delete_text
        Pryline.point = 0
        Pryline.redisplay
        Pryline.insert_text buffer
        Pryline.insert_text "\n"
      end
      Pryline.accept_line
    else
      left_of_cursor = Pryline.line_buffer[0...Pryline.point]
      right_of_cursor = Pryline.line_buffer[(Pryline.point)..-1] || ''
      Pryline.delete_text
      Pryline.point = 0
      Pryline.redisplay

      indent = Pry::Indent.new
      left = indent.indent(left_of_cursor)
      Pryline.insert_text(left)
      Pryline.insert_text "\n#{indent.current_prefix}"

      if right_of_cursor.strip != ''
        point = Pryline.point
        right = indent.indent(right_of_cursor.strip)
        Pryline.insert_text(right.chomp.to_s)
        Pryline.point = point
      end

    end
  rescue SyntaxError
    str = StringIO.new
    p = Pry.new(output: str, pager: false)
    preamble = "# syntax error in the below\n"
    new_buffer = Pry::Editor.new(p).edit_tempfile_with_content("#{preamble}#{whole_buffer}", whole_buffer.lines.count)
    new_buffer.delete_prefix!(preamble)
    pry_instance.eval_string = ''
    Pryline.delete_text
    Pryline.point = 0
    Pryline.redisplay
    Pryline.insert_text new_buffer.chomp
    Pryline.refresh_line
    Pryline.redisplay
  end
end
```
Now, whenever you hit "enter," you check to see if the expression you've input is a complete expression - if not, insert a newline literal, allowing multi-line editing.

**Comment by kevintraver** [comment]
Thank you for the explanation!
